language: android
os: linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: Lint and Test
      if: type = pull_request
      before_install:
        - nvm install 12 && node --version
      install: yarn
      script: yarn lint && yarn test
    - stage: Publish to NPM
      if: type = push AND branch = master
      before_install:
        - nvm install 12 && node --version
      install: yarn
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn release
    - stage: Push Alpha Tag
      if: type = push AND branch = develop AND tag IS blank
      android: 
        components:
        - build-tools-28.0.3
        - android-28
        - extra-android-m2repository
        - extra-google-google_play_services
        - extra-google-m2repository
        - addon-google_apis-google-16
      before_install:
        - nvm install 12 && node --version
      install: yarn
      script: ./.travis/utils/fix-max-file-watch.sh && cd android && ./gradlew assembleRelease
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@travis-ci.org"
        - git remote rm origin
        - git remote add origin https://$GITHUB_API_USER:$GH_TOKEN@github.com/natura-cosmeticos/natds-rn
        - git fetch
        - git checkout $TRAVIS_BRANCH
        - LATEST_TAG=`git tag --sort=committerdate | tail -1`
        - NEXT_TAG=`node $TRAVIS_BUILD_DIR/.travis/utils/build-alpha-version.js ${LATEST_TAG}`
        - export TRAVIS_TAG=$NEXT_TAG
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: "$GH_TOKEN"
        file: "$TRAVIS_BUILD_DIR/android/app/build/outputs/apk/release/app-release.apk"
        skip_cleanup: true
        draft: false
        on:
          repo: natura-cosmeticos/natds-rn
          branch: develop
