language: javascript
os: linux

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules/

jobs:
  include:
    - stage: Lint and Test
      if: type = pull_request
      before_install:
        - nvm install 12 && node --version
      install: yarn
      script: yarn lint && yarn test
    - stage: Publish to NPM
      if: type = push AND branch = master
      before_install:
        - nvm install 12 && node --version
      install: yarn
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn build && yarn release
